# Resources: https://docs.streamlit.io/develop/api-reference/configuration/config.toml
# https://www.youtube.com/watch?v=9n4Ch2Dgex0

[theme]
# Primary accent color
primaryColor = "#f5cc00"

# Background color for the main content area
backgroundColor = "#f4f1de"

# Secondary background color for the sidebar
secondaryBackgroundColor = "#003566"

# Text color
textColor = "#fffdf7"

# Font family for all text in the app
font = "Montserrat"
